theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
text-width = 120
end-of-line-diagnostics = "hint"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.inline-diagnostics]
cursor-line="error"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control","file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "separator", "spacer", "position-percentage", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
